### ISSUE TITLE
rcomp .ignore file (or ignore dotfiles? or both?) 

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/rcomp#29]
rcomp thinks my OSX .DS_Store files are tests. Perhaps it should ignore files that begin with a dot. Maybe it would be nice to have a .rcompignore file too?

**Comment by cknadler** [comment]
Wow, nice catch. Didn't think I would be bumping the version so soon. Working on a fix now.

**Comment by cknadler** [comment]
I'm going to bump to `0.1.1` with just ignoring all files that start with a `.`

For `0.2.0` I'm debating on either a `.rcompignore` file (such a long file name) or having `ignore:` be a configuration option in the `.rcomp` file. Thoughts?

**Comment by russplaysguitar** [comment]
i like option 2 best, nice to keep all config in the same place

**Comment by cknadler** [comment]
Me too. I'll pull it into an issue. `0.1.1` should be up in a few as well.

**Comment by cknadler** [comment]
`0.1.1` is up and fixes this problem for now. See #30 for further discussion on ignored files / patterns.

**Comment by russplaysguitar** [comment]
nice work
